### ISSUE TITLE
Can't download from bintray

### ISSUE THREAD

**Issue by RobbWatershed** [omicronapps/7-Zip-JBinding-4Android#11]
I realized today that all resources hosted on bintray are inaccessible : bintray returns a 403 forbidden

e.g. https://dl.bintray.com/omicronapps/7-Zip-JBinding-4Android/net/sf/sevenzipjbinding/sevenzipjbinding/16.02-2.02/sevenzipjbinding-16.02-2.02.pom

This is kinda critical as my app's CI won't build if bintray can't serve the required files.

From what I've read elswhere (https://github.com/jeremylong/DependencyCheck/issues/2739), it might be that your account hit a rate limit...

Could you do something to fix it quickly ? 

NB : Bintray will apparently disappear in favour of jfrog, starting from July 4th

**Comment by omicronapps** [comment]
I'm afraid it looks like JFrog Bintray services are no longer be available as of May 1st, 2021:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

However, it should be possible to use JitPack instead to consume the AAR libraries:

https://jitpack.io/#omicronapps/7-Zip-JBinding-4Android/Release-16.02-2.02
> **Step 1.** Add the JitPack repository to your build file
> Add it in your root build.gradle at the end of repositories:
```
	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```
> **Step 2.** Add the dependency
```
	dependencies {
	        implementation 'com.github.omicronapps:7-Zip-JBinding-4Android:Release-16.02-2.02'
	}
```

I tested this locally and I was able to build an application using the JitPack repository.
Please let me know if this works, and I will update the documentation.

**Comment by RobbWatershed** [comment]
I confirm it does work with that new host, thanks !
