### ISSUE TITLE
wrong password

### ISSUE THREAD

**Issue by pickupsb** [omicronapps/7-Zip-JBinding-4Android#19]
im trying to pass a password from java level but it gives  the error wrong password. did i miss anything?
public void testExtractencrypt(File file,String password) {
        try {
            RandomAccessFile randomAccessFile = new RandomAccessFile(file, "r");
            RandomAccessFileInStream inStream = new RandomAccessFileInStream(randomAccessFile);
//            IInArchive inArchive = null;
//            ArchiveOpenCallback callback = new ArchiveOpenCallback();

            IInArchive inArchive = SevenZip.openInArchive(ArchiveFormat.ZIP, inStream, password);
//            IInArchive inArchive = SevenZip.openInArchive(ArchiveFormat.ZIP, inStream, password);
            ArchiveExtractCallback extractCallback = new ArchiveExtractCallback();
            inArchive.extract(null, false, extractCallback);
            inArchive.close();
            inStream.close();
        } catch (FileNotFoundException e) {
            Log.e(TAG, e.getMessage());
        } catch (SevenZipException e) {
            Log.e(TAG, e.getMessage());
        } catch (IOException e) {
            Log.e(TAG, e.getMessage());
        }
    }

**Comment by omicronapps** [comment]
It appears that you may have resolved this already.

But for reference, there is a discussion on the use of passwords in [7-Zip-JBinding](https://sourceforge.net/p/sevenzipjbind/) here:
https://sourceforge.net/p/sevenzipjbind/discussion/757965/thread/cb57da04/
