### ISSUE TITLE
Creating 7z password protected archives and RAR5 support

### ISSUE THREAD

**Issue by Kitsune2222** [omicronapps/7-Zip-JBinding-4Android#2]
Do you plan update 7zip-JBinding to newer versions which support RAR5 and 7z creating with password? This functions will be actual. And thanks for work!

**Comment by omicronapps** [comment]
If support for that gets implemented in a future revision of [7-Zip-JBinding](https://github.com/borisbrodski/sevenzipjbinding), then yes, I can merge and port that over to 7-Zip-JBinding-4Android.

**Comment by Kitsune2222** [comment]
Seems  7-Zip-JBinding suppot it. https://github.com/borisbrodski/sevenzipjbinding/commit/23dccd1a7462ca584c4305aa564696378daa3a42
https://github.com/borisbrodski/sevenzipjbinding/commit/d7ae87db3a5563892f9b0d99ecb028faeba2db08

**Comment by omicronapps** [comment]
Ok, so there is a version "16.02-2.01beta" in the works, but not yet released. Let me take a look at merging that with the Android port.

**Comment by omicronapps** [comment]
Merged over 16.02-2.01beta with commit [efdc5b9c9e8ecba5a80ff7c942ae165f554cbeba](https://github.com/omicronapps/7-Zip-JBinding-4Android/commit/efdc5b9c9e8ecba5a80ff7c942ae165f554cbeba). This is still a beta version, but looks like 16.02-2.01 release is currently being prepared.

**Comment by Kitsune2222** [comment]
Thank you!
