### ISSUE TITLE
How can I get all the extracted File objects?

### ISSUE THREAD

**Issue by asthagarg2428** [omicronapps/7-Zip-JBinding-4Android#20]
Hi Team,

I have gone through the Documentation and I'm using this library in my Android project but I have few doubts.

In extraction, how can I get all the extracted files? All I can see is the file name and length are printed but how can I get the File object?
Because in App the UI would be such that the extracted files are shown to user and he can click on them to view also.

Looking forward for quick reply :)

**Comment by omicronapps** [comment]
Examples for how to extract all files are provided in the official documentation for 7-Zip-JBinding here:
- [Extracting archive using standard interface and call back method as a filter](http://sevenzipjbind.sourceforge.net/extraction_snippets.html#extracting-archive-std-int-callback)

And also in an example included with 7-Zip-JBinding-4Android here:
- [File extraction, standard interface](https://github.com/omicronapps/7-Zip-JBinding-4Android)

The file object (data) is provided through the [write()](http://sevenzipjbind.sourceforge.net/javadoc/net/sf/sevenzipjbinding/ISequentialOutStream.html#write(byte[])) method of the ISequentialOutStream interface.
