### ISSUE TITLE
Unable to compress file types other than txt

### ISSUE THREAD

**Issue by asthagarg2428** [omicronapps/7-Zip-JBinding-4Android#21]
I tried compression with 1 docx and other mp4 files and on extracting the same compressed files, the obtained files can't be viewed.

Steps:-
1. I changed the create method of `CompressArchiveStructure.java` to return me the Items containing files from assets folder of type docx and mp4. 
```
public static Item[] create(Context context) {


        Item[] items = new Item[2];
        try {
            String file1 = Helper.getDocFileFromAsset(context).getPath();
            items[0] = new Item(file1, Helper.getStringFromFile(file1));
            String file2 = Helper.getMP4FileFromAsset(context).getPath();
            items[1] = new Item(file2, Helper.getStringFromFile(file2));
         
        } catch (Exception e) {
            e.printStackTrace();
        }
        return items;
    }
```

2. Calling compress with ZIP format from `MainActivity`
```
CompressGeneric().compress(
            "${Environment.getExternalStorageDirectory()}/Download/demo/compressed_zip.zip",
            "ZIP", 2, this
        )
```

3. Run the App, You will see thet the compressed_zip.zip is generated at the right path and extract the zip files using phone's default App

Observed behaviour:-
1. The files obtained ater extraction can't be viewed
2. The extracted files are under the directory structure _compressed_zip>data>user>0>com.example.MyProject>files._ (which is the path of the file I picked from Asset folder) Ideally it should be directly under  compressed_zip folder.

Please help me resolving in this issue and let me know if you need any more details from my side

**Comment by asthagarg2428** [comment]
1st part I have resolved.
Created separate issue for 2nd point

**Comment by omicronapps** [comment]
I can also recommend referring to the documentation for Java library [7-Zip-JBinding](http://sevenzipjbind.sourceforge.net/).

This includes the the documentation available here:
- [Documentation](http://sevenzipjbind.sourceforge.net/first_steps.html)

As well as the Java documentation for the library:
- [JavaDoc](http://sevenzipjbind.sourceforge.net/javadoc/)
