### ISSUE TITLE
Is there any way to stop the extraction process?

### ISSUE THREAD

**Issue by zhoushunli** [omicronapps/7-Zip-JBinding-4Android#4]
Hello, i wonder if there is any way to stop the extraction, eg. when a very large archive is being extracted, and i want to cancel this process, is it possible to achive this? thank you in advance.

**Comment by omicronapps** [comment]
Look at the [IArchiveExtractCallback](https://github.com/omicronapps/7-Zip-JBinding-4Android/blob/master/sevenzipjbinding/src/main/java/net/sf/sevenzipjbinding/IArchiveExtractCallback.java) callbacks as well as write() in [ISequentialOutStream](https://github.com/omicronapps/7-Zip-JBinding-4Android/blob/master/sevenzipjbinding/src/main/java/net/sf/sevenzipjbinding/ISequentialOutStream.java). There are various places here where a [SevenZipException](https://github.com/omicronapps/7-Zip-JBinding-4Android/blob/master/sevenzipjbinding/src/main/java/net/sf/sevenzipjbinding/SevenZipException.java) can be thrown to stop the extraction, depending on when you want this to happen.

**Comment by omicronapps** [comment]
Please let me know if this answers your question, and this issue can be resolved.
